const Menu = [
    {
        'title': 'Top Served',
        'image': 'images/chicken-biriyani.jpeg',
        'item1': 'Chicken Biriyani',
        'item2': 'Masala Dosa',
        'item3': 'Chicken Fried Rice',
        'item4': 'Paneer Butter Masala',
        'desc': 'perfect fuel... If you are looking for the most delicious dishes then here is a list of most ordered foods from our valuable cusomers.',
    },
    {
        'title': 'Instant Hunger',
        'image': 'images/gulab-jamun.jpg',
        'item1': 'Gulab Jamun',
        'item2': 'Samosa',
        'item3': 'Pakoda',
        "item4": 'Maggie',
        'desc': 'HUNGRY! then what are you looking for.....<br>these instant yummy dishes are for you.',
    },
    {
        'title': 'Must Try in India',
        'image': 'images/vada-pav.jpg',
        'item1': 'Dal Makhani',
        'item2': 'Vada Pav',
        'item3': 'Dhokla',
        "item4": 'Korma-Paratha',
        'desc': 'What to eat in India...??<br>we want you once try these awesome dishes consisting of major regional foods of India.<br>Indian cuisine consists of a variety of regional and traditional cuisines native to the Indian subcontinent.',
    },
    {
        'title': 'Northern Swad',
        'image': 'images/chole-Bhature.jpg',
        'item1': 'Chole Bhature',
        'item2': 'Kashmiri Rogan Josh',
        'item3': 'Dilli ki chat',
        "item4": 'Rajasthani Dal Bati',
        'desc': 'enjoy a taste of heaven...<br>North Indian curries usually have thick, moderately spicy and creamy gravies. The use of dried fruits and nuts is fairly common even in everyday foods. Dairy products like milk, cream, cottage cheese, ghee (clarified butter) and yogurt play an important role in the cooking',
    },
    {
        'title': 'Chinese Food',
        'image': 'images/momos.jpg',
        'item1': 'Machurian',
        'item2': 'Momos',
        'item3': 'Chowmein',
        "item4": 'Schezwan Noodles',
        'desc': 'goodies for the foodies...try best combo or indo-chinese food here. do try our famous MOMOS, then you will say....I love Momos. I want to marry it, but it would just be to eat her family at the wedding.',
    },
    {
        'title': 'Sumptuous South Indian',
        'image': 'images/idlidosa.jpg',
        'item1': 'Hyderabadi Biryani',
        'item2': 'Andhra Style Chicken Curry',
        'item3': 'Idli and Dosa',
        "item4": 'Uttapam',
        'desc': 'wanna try something spicy....?<br>Southern India has many diverse food traditions. don&apos;t forget sambhar',
    },
    {
        'title': 'North-Eastern Taste',
        'image': 'images/Khar.jpg',
        'item1': 'Khar from Assam',
        'item2': 'Thukpa from AP',
        'item3': 'Kelli Chana- Spicy peas from Manipur',
        "item4": 'Jadoh from Meghalaya',
        'desc': 'Bland, but also hot; pungent, but also aromatic; healthy, but also fatty—these antithetical adjectives can all be used to describe a meal from the Northeast, which is incomplete without a steaming platter of rice and various green vegetables',
    },
    {
        'title': 'Delicious Pickup',
        'image': 'images/pizza-burger.jpg',
        'item1': 'Pizza',
        'item2': 'Burger',
        'item3': 'Frakiee',
        "item4": 'Pani-Puri',
        'desc': 'The good just got better! Treat yourself to the premium taste of the Burger Pizza, that looks good and tastes great with paneer and red paprika.',
    },
    {
        'title': 'Desserts',
        'image': 'images/gajar-ka-halwa.jpg',
        'item1': 'Kaju ki Barfi',
        'item2': 'Gajar ka Halwa',
        'item3': 'Kulfi',
        "item4": 'Modak',
        'desc': 'Good Food, Good Mood. <br>Bite into delight! Witness the epic taste of sweets',
    },
]

export default Menu;